apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
spec:
  type: NodePort
  selector:
    app: my-nodejs-app
  ports:
    - port: 80 # The port on which the service is exposed
      targetPort: 3000 # This should match the port in your app's code
